name: Lint

on:
  - pull_request

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Setup Matchers
        run: |
          echo "::add-matcher::.github/workflows/matchers/black.json"
          echo "TERM: changing from $TERM -> xterm"
          export TERM=xterm
      - name: Install dependencies
        run: |
          pip install black
      - name: Run black
        run: |
          black --check .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Setup Matchers
        run: |
          echo "::add-matcher::.github/workflows/matchers/mypy.json"
          echo "TERM: changing from $TERM -> xterm"
          export TERM=xterm
      - name: Install dependencies
        run: |
          pip install mypy
      - name: Run mypy
        run: |
          mypy --show-column-numbers .

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Setup Matchers
        run: |
          echo "::add-matcher::.github/workflows/matchers/ruff.json"
          echo "TERM: changing from $TERM -> xterm"
          export TERM=xterm
      - name: Install dependencies
        run: |
          pip install ruff
      - name: Run ruff
        run: |
          ruff .
